//
//  KillSwitchManager.swift
//  Waypoint
//  System-wide kill switch: while the proxy is up, a pf anchor drops any
//  egress traffic that would bypass Waypoint. The rules text is composed here
//  and executed by the privileged helper (pfctl needs root); the helper also
//  tears everything down on disconnect/crash so the machine can't be locked
//  out of the network.
//

import Foundation

@MainActor
final class KillSwitchManager {
    static let shared = KillSwitchManager()

    private init() {}

    /// Installs the anchor with rules for the current runtime shape
    /// (TUN vs system proxy, allow-LAN). Returns nil on success.
    func applyNow() async -> String? {
        let rules = Self.buildRules()
        return await withCheckedContinuation { (continuation: CheckedContinuation<String?, Never>) in
            guard let helper = PrivilegedHelperManager.shared.helper(failture: { message in
                continuation.resume(returning: "proxy helper unavailable: \(message)")
            }) else {
                continuation.resume(returning: "proxy helper unavailable")
                return
            }
            helper.setFirewallKillSwitch(rules) { errorMessage in
                if let errorMessage, !errorMessage.isEmpty {
                    continuation.resume(returning: errorMessage)
                } else {
                    continuation.resume(returning: nil)
                }
            }
        }
    }

    func clear() async {
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            guard let helper = PrivilegedHelperManager.shared.helper(failture: { _ in
                continuation.resume()
            }) else {
                continuation.resume()
                return
            }
            helper.clearFirewallKillSwitch { _ in
                continuation.resume()
            }
        }
    }
}

extension KillSwitchManager {
    /// The full anchor ruleset. Order matters — pf applies first match, and the
    /// trailing `block drop out all` is what makes bypass attempts fail closed.
    static func buildRules() -> String {
        var lines = [
            "# Generated by Waypoint — do not edit.",
            // Loopback carries all traffic to Waypoint's own local ports.
            "pass on lo0 all no state",
            // DHCP lease renewal.
            "pass out proto udp from any port 68 to any port 67 no state",
            // Upstream sockets of privileged processes (the core runs as root
            // under TUN mode and must reach its remote proxies).
            "pass out user root no state",
            // This app's own upstream sockets (system-proxy mode spawns the
            // core under our uid).
            "pass out user \(getuid()) no state",
            // macOS system resolvers in system-proxy mode.
            "pass out user _mdnsresponder no state",
            "pass out user _mdnssd no state",
            // TUN devices carry every proxied packet; enumerate rather than
            // race the core picking its device index.
            "pass out on { utun0 utun1 utun2 utun3 utun4 utun5 utun6 utun7 } no state",
            "pass out on { utun8 utun9 utun10 utun11 utun12 utun13 utun14 utun15 } no state",
        ]
        if ConfigManager.allowConnectFromLan {
            lines.append("pass out to { 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12 } no state")
        }
        lines.append("# Drop anything that would bypass Waypoint.")
        lines.append("block drop out all")
        return lines.joined(separator: "\n") + "\n"
    }
}
