/// Pure composition of the pf anchor ruleset for the kill switch. The
/// privileged helper only executes the returned text (`pfctl -a … -f`).
public enum KillSwitchRules {
    /// Order matters — pf applies first match, and the trailing
    /// `block drop out all` is what makes bypass attempts fail closed.
    public static func compose(uid: UInt32, allowsLan: Bool) -> String {
        var lines = [
            "# Generated by Waypoint — do not edit.",
            // Loopback carries all traffic to Waypoint's own local ports.
            "pass on lo0 all no state",
            // DHCP lease renewal.
            "pass out proto udp from any port 68 to any port 67 no state",
            // Upstream sockets of privileged processes (the core runs as root
            // under TUN mode and must reach its remote proxies).
            "pass out user root no state",
            // This app's own upstream sockets (system-proxy mode spawns the
            // core under our uid).
            "pass out user \(uid) no state",
            // macOS system resolvers in system-proxy mode.
            "pass out user _mdnsresponder no state",
            "pass out user _mdnssd no state",
            // TUN devices carry every proxied packet; enumerate rather than
            // race the core picking its device index.
            "pass out on { utun0 utun1 utun2 utun3 utun4 utun5 utun6 utun7 } no state",
            "pass out on { utun8 utun9 utun10 utun11 utun12 utun13 utun14 utun15 } no state",
        ]
        if allowsLan {
            lines.append("pass out to { 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12 } no state")
        }
        lines.append("# Drop anything that would bypass Waypoint.")
        lines.append("block drop out all")
        return lines.joined(separator: "\n") + "\n"
    }
}
