/// Pure composition of the pf anchor ruleset for the kill switch. The
/// privileged helper only executes the returned text (`pfctl -a … -f`).
public enum KillSwitchRules {
    /// pf resolves `pass`/`block` by the **last** matching rule, not the first
    /// (`pf.conf(5)`: "For block and pass, the last matching rule decides what
    /// action is taken"). The trailing catch-all `block drop out all` therefore
    /// matches every outbound packet, so without `quick` on the exceptions it
    /// would win over all of them and drop the whole machine's traffic,
    /// loopback and the core's own sockets included. `quick` makes a rule
    /// terminal, which is what gives the intended "everything except these
    /// specific flows is blocked".
    public static func compose(uid: UInt32, allowsLan: Bool) -> String {
        var lines = [
            "# Generated by Waypoint — do not edit.",
            // Loopback carries all traffic to Waypoint's own local ports.
            "pass quick on lo0 all no state",
            // DHCP lease renewal.
            "pass out quick proto udp from any port 68 to any port 67 no state",
            // Upstream sockets of privileged processes (the core runs as root
            // under TUN mode and must reach its remote proxies).
            "pass out quick user root no state",
            // This app's own upstream sockets (system-proxy mode spawns the
            // core under our uid).
            "pass out quick user \(uid) no state",
            // macOS system resolvers in system-proxy mode.
            "pass out quick user _mdnsresponder no state",
            "pass out quick user _mdnssd no state",
            // TUN devices carry every proxied packet; enumerate rather than
            // race the core picking its device index.
            "pass out quick on { utun0 utun1 utun2 utun3 utun4 utun5 utun6 utun7 } no state",
            "pass out quick on { utun8 utun9 utun10 utun11 utun12 utun13 utun14 utun15 } no state",
        ]
        if allowsLan {
            lines.append("pass out quick to { 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12 } no state")
        }
        lines.append("# Drop anything that would bypass Waypoint.")
        lines.append("block drop out all")
        return lines.joined(separator: "\n") + "\n"
    }
}
